### ISSUE TITLE
selenium 3.0.0b1 supports python 3

### ISSUE THREAD

**Issue by josephsu** [ubershmekel/python3wos#43]
https://pypi.python.org/pypi/selenium

**Comment by cclauss** [comment]
Hi @josephsu 

At the bottom of http://python3wos.appspot.com/ it says " If a module is red though it supports python 3 it's because they don't have the "Programming Language :: Python :: 3" tag. Consider contacting the maintainer to fix this."  this is the problem for Selenium.  It's PyPI page does not have the "Programming Language :: Python :: 3" trove classifier that python3wos is looking for.

**Comment by cclauss** [comment]
This problem is now fixed on the Selenium side. See https://github.com/SeleniumHQ/selenium/issues/2546
